<?php

/**
 * @file
 * Defines management/helper/display functions for page like content.
 */

/**
 * Implements hook_menu().
 */
function islandora_paged_content_menu() {
  return array(
    'admin/islandora/paged_content' => array(
      'title' => 'Paged Content Module',
      'description' => 'Configuration for the Paged Content solution pack.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_paged_content_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_paged_content_theme() {
  return array(
    'islandora_paged_content_manage_pages_sequences_form' => array(
      'render element' => 'form',
      'file' => 'theme/theme.inc',
    ),
  );
}

/**
 * Checks whether the user can access the "manage page" page.
 *
 * @return bool
 *   TRUE if they can access, FALSE otherwise.
 */
function islandora_paged_content_manage_page_access_callback($object, array $content_models) {
  $permissions = array(FEDORA_ADD_DS, FEDORA_METADATA_EDIT, FEDORA_PURGE);
  return islandora_user_access($object, $permissions, $content_models);
}

/**
 * Checks whether the user can access the "manage pages" page.
 *
 * @return bool
 *   TRUE if they can access, FALSE otherwise.
 */
function islandora_paged_content_manage_pages_access_callback($object, array $content_models) {
  $permissions = array(FEDORA_ADD_DS, FEDORA_METADATA_EDIT, FEDORA_PURGE, FEDORA_INGEST);
  return islandora_user_access($object, $permissions, $content_models);
}

/**
 * Search the given objects HOCR for the given term and coordinate data.
 *
 * It only works on exact term matches.
 *
 * @param FedoraObject $object
 *   The object to apply the search to.
 * @param string $term
 *   The term to search for.
 * @param string $hocr_dsid
 *   The HOCR datastream id.
 *
 * @return array
 *   $highlighting_info The coordinates of the matches to the term.
 */
function islandora_paged_content_get_highlighting_info($object, $term, $hocr_dsid = 'HOCR') {
  if (module_exists('islandora_ocr') && isset($object[$hocr_dsid])) {
    $highlighting_info = array();
    $hocr = HOCR::fromDatastream($object[$hocr_dsid]);
    $highlighting_info['bounding_boxes'] = $hocr->search($term);
    // @todo Sort this nonsense.
    // $page = $hocr->search($term, array('ocrx_page'));
    // $highlighting_info['width'] = intval($[5]);
    // $highlighting_info['height'] = intval($values[6]);
  }
  return array();
}
